version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: yii2-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHP_ENABLE_XDEBUG=0
    depends_on:
      - db

  web:
    image: nginx:1.25
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: yii2-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2app
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
